"""
Django settings for mesilat_zion_farm_website project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
FEEDBACK_URL = os.getenv("FEEDBACK_URL", "https://mesilatzionfarm.co.il/reviews/")
SEND_EMAIL = os.getenv("SEND_EMAIL", "False") == "True"
SEND_SMS = os.getenv("SEND_SMS", "False") == "True"
NTFY_URL = os.getenv("NTFY_URL", "https://ntfy.sh").rstrip("/")
NTFY_TOPIC = os.getenv("NTFY_TOPIC", "")
NTFY_PRIORITY = int(os.getenv("NTFY_PRIORITY", "5"))
NUMBER_OF_HORSES = int(os.getenv("NUMBER_OF_HORSES", "5"))

GOOGLE_PLACE_ID = os.getenv("GOOGLE_PLACE_ID", "PASTE_YOUR_PLACE_ID_HERE")
GOOGLE_PLACES_API_KEY = os.getenv("GOOGLE_PLACES_API_KEY", "")

DEBUG = os.environ.get("DEBUG", "False") == "True"

SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "insecure-dev-key-do-not-use-in-production"
    else:
        raise RuntimeError("SECRET_KEY חייב להיות מוגדר בפרודקשן")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "DEBUG" if DEBUG else "WARNING"},
    "loggers": {"django": {"handlers": ["console"], "level": "INFO", "propagate": False}},
}


STATIC_ROOT = BASE_DIR / "staticfiles"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# רשימת מקורות מהימנים ל-CSRF (חובה ל-Django 4+ עבור POST מדומיין אמיתי).
# פורמט: כתובת מלאה כולל https://, מופרדות בפסיקים.
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if origin.strip()
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django_ratelimit',
    'homePage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'homePage.middleware.ShabbatClosureMiddleware',
]

ROOT_URLCONF = 'mesilat_zion_farm_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'homePage.context_processors.site_settings',

            ],
        },
    },
]

WSGI_APPLICATION = 'mesilat_zion_farm_website.wsgi.application'


DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        # SSL רלוונטי רק כשיש DATABASE_URL אמיתי (Postgres) — SQLite לא מכיר sslmode
        ssl_require=bool(os.getenv("DATABASE_URL")) and not DEBUG,
    )
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ADMIN_MODEL_ORDER = {
    "homePage": {
        "object_name": [
            "SiteSettings", "ScheduleBoard", "Booking", "Receipt", "CancellationRequest",
        ],
    }
}

# עמוד הבית של האדמין: קיבוץ המודלים לתיקיות ניתנות לקיפול/פתיחה, בסדר הזה.
# מודל שלא רשום כאן נופל לקבוצת "אחר" בסוף.
ADMIN_MODEL_GROUPS = {
    "homePage": [
        ("הזמנות ולוח זמנים", ["SiteSettings", "ScheduleBoard", "Booking", "CancellationRequest", "Appointment",
                                "CustomSchedule", "BusinessHours", "Weekday", "ActivityRule"]),
        ("כספים", ["Receipt", "Payment", "MonthlySummary"]),
        ("פעילויות ומדריכים", ["Activity", "Instructor", "TreatmentSession"]),
        ("ביקורות והסכמות", ["SiteReview", "TermsConsent", "MarketingConsent"]),
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'he'

TIME_ZONE = "Asia/Jerusalem"

USE_I18N = True

USE_TZ = True

PAYMENT_PROVIDER = os.getenv("PAYMENT_PROVIDER", "mock")  # שנה ל-"payplus" בפרודקשן

# שני סטים של מפתחות חיים ב-.env בו-זמנית (test + production) — הבחירה ביניהם
# אוטומטית לפי DEBUG, כדי שלא יהיה צורך להחליף ערכים ידנית בין הסביבות.
# PAYPLUS_SANDBOX_OVERRIDE: מתג נפרד מ-DEBUG לצורך בדיקות זמניות באתר החי (Render) —
# מאפשר להשתמש ב-SANDBOX של PayPlus בפרודקשן בלי לגעת ב-DEBUG (שמשפיע גם על אבטחה/לוגים).
# ברירת המחדל היא False, כך שההתנהגות הקיימת לא משתנה אלא אם מגדירים את המשתנה במפורש.
PAYPLUS_SANDBOX_OVERRIDE = os.getenv("PAYPLUS_SANDBOX_OVERRIDE", "False") == "True"

if DEBUG or PAYPLUS_SANDBOX_OVERRIDE:
    PAYPLUS_API_KEY          = os.getenv("PAYPLUS_TEST_API_KEY", "")
    PAYPLUS_SECRET_KEY       = os.getenv("PAYPLUS_TEST_SECRET_KEY", "")
    PAYPLUS_PAYMENT_PAGE_UID = os.getenv("PAYPLUS_TEST_PAYMENT_PAGE_UID", "")
    PAYPLUS_BASE_URL         = "https://restapidev.payplus.co.il/api/v1.0"
else:
    PAYPLUS_API_KEY          = os.getenv("PAYPLUS_PROD_API_KEY", "")
    PAYPLUS_SECRET_KEY       = os.getenv("PAYPLUS_PROD_SECRET_KEY", "")
    PAYPLUS_PAYMENT_PAGE_UID = os.getenv("PAYPLUS_PROD_PAYMENT_PAGE_UID", "")
    PAYPLUS_BASE_URL         = "https://restapi.payplus.co.il/api/v1.0"


# ==== Policy Versions (for consent & UI logic) ====
TERMS_VERSION   = "1.3"      # עדכני כשמשנים את תנאי השימוש
PRIVACY_VERSION = "1.2"      # עדכני כשמשנים את מדיניות הפרטיות
MARKETING_VERSION = "1.3"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# הערה: אין צורך ב-STATICFILES_DIRS ל-homePage/static — הוא כבר מתגלה
# אוטומטית ע"י AppDirectoriesFinder (homePage היא app מותקנת).

if os.getenv("EMAIL_BACKEND", "smtp") == "console":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-ratelimit דורש cache backend משותף בין תהליכים (לא locmem).
# FileBasedCache משותף בין worker processes אך לא תומך ב-increment אטומי;
# עבור עומס גבוה יותר כדאי לשדרג ל-Redis/Memcached (django-redis).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": str(BASE_DIR / "django_cache"),
    }
}
SILENCED_SYSTEM_CHECKS = ["django_ratelimit.E003"]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ---- הגדרות אבטחה לפרודקשן ----
# מותנה גם ב-RENDER (משתנה שה-Render מגדיר אוטומטית) ולא רק ב-DEBUG, כדי שאפשר יהיה
# להריץ מקומית עם DEBUG=False (למשל לבדיקת מפתחות production) בלי הפניית HTTPS שבורה,
# כי runserver המקומי לא מגיש TLS בכלל.
if not DEBUG and os.getenv("RENDER"):
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000          # שנה
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    # Render הוא reverse proxy — מספר לג'נגו איך לזהות HTTPS
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")