# Generated by Django 5.2.4 on 2025-08-07 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_participants', models.IntegerField(default=1)),
                ('max_participants', models.IntegerField(default=6)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('activity_type', models.CharField(choices=[('basic', 'מתחילים'), ('advanced', 'מתקדמים'), ('standard', 'רגילה'), ('special', 'מיוחדת (שעה וחצי)')], default='standard', max_length=20)),
                ('duration_minutes', models.IntegerField(choices=[(15, '15 דקות'), (30, '30 דקות'), (45, '45 דקות'), (60, 'שעה'), (90, 'שעה וחצי')], default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('is_break', models.BooleanField(default=False)),
                ('participants_count', models.IntegerField(default=1)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homePage.activity')),
            ],
        ),
    ]
