# Generated by Django 5.2.4 on 2025-08-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_activity_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('basic', 'מתחילים'), ('advanced', 'מתקדמים'), ('white', 'סוס לבן'), ('brown', 'סוס חום'), ('couple', 'רכיבה זוגית ביום'), ('couple_sunrise', 'רכיבה זוגית בזריחה'), ('couple_night', 'רכיבה זוגית בלילה'), ('none', 'ללא סוג')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_minutes',
            field=models.IntegerField(choices=[(15, '15 דקות'), (30, '30 דקות'), (45, '45 דקות'), (60, 'שעה'), (90, 'שעה וחצי'), (120, 'שעתיים')], default=30),
        ),
    ]
