# Generated by Django 5.2.4 on 2025-08-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_customschedule_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
