# Generated by Django 5.2.4 on 2025-08-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_appointment_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='activity',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
