# Generated by Django 5.2.4 on 2025-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_remove_appointment_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_minutes',
            field=models.IntegerField(choices=[(10, '10 דקות'), (30, '30 דקות'), (45, '45 דקות'), (60, 'שעה'), (90, 'שעה וחצי'), (120, 'שעתיים')], default=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
