# Generated by Django 5.2.4 on 2025-08-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_alter_activity_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='homePage.activity'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
