# Generated by Django 5.2.4 on 2025-08-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0007_appointment_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='participants_count',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('summer', 'קיץ'), ('winter', 'חורף')], max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'שני'), (1, 'שלישי'), (2, 'רביעי'), (3, 'חמישי'), (4, 'שישי'), (5, 'שבת'), (6, 'ראשון')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'שעות עבודה כלליות',
                'verbose_name_plural': 'שעות עבודה כלליות',
                'unique_together': {('season', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='ActivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('summer', 'קיץ'), ('winter', 'חורף')], max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'שני'), (1, 'שלישי'), (2, 'רביעי'), (3, 'חמישי'), (4, 'שישי'), (5, 'שבת'), (6, 'ראשון')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('end_is_midnight_next_day', models.BooleanField(default=False, help_text='אם מסמנים, הסיום הוא 24:00 (00:00 שלמחרת). שימושי לרכיבת לילה.')),
                ('assigned_only', models.BooleanField(default=False, help_text='אם מסומן – להציג רק תורים ששויכו לפעילות הזו (לא בריכה משותפת).')),
                ('booking_cutoff_minutes', models.PositiveIntegerField(default=0, help_text='מספר דקות מינימום מראש להזמנה (למשל 60 לדקה).')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='homePage.activity')),
            ],
            options={
                'verbose_name': 'כלל פעילות',
                'verbose_name_plural': 'כללי פעילות',
                'unique_together': {('activity', 'season', 'day_of_week')},
            },
        ),
    ]
