# Generated by Django 5.2.4 on 2025-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_alter_appointment_participants_count_businesshours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'יום בשבוע',
                'verbose_name_plural': 'ימים בשבוע',
                'ordering': ['code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityrule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='activityrule',
            name='assigned_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activityrule',
            name='booking_cutoff_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityrule',
            name='end_is_midnight_next_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityrule',
            name='days',
            field=models.ManyToManyField(related_name='activity_rules', to='homePage.weekday'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='days',
            field=models.ManyToManyField(related_name='business_hours', to='homePage.weekday'),
        ),
        migrations.RemoveField(
            model_name='activityrule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='day_of_week',
        ),
    ]
