# Generated by Django 5.2.4 on 2025-08-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0009_weekday_alter_activityrule_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='google', max_length=32)),
                ('review_id', models.CharField(max_length=64, unique=True)),
                ('author_name', models.CharField(max_length=128)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField(blank=True)),
                ('time', models.DateTimeField()),
                ('profile_photo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='google', max_length=32)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Stats',
                'verbose_name_plural': 'Review Stats',
            },
        ),
    ]
