# Generated by Django 5.2.4 on 2025-08-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0011_delete_review_delete_reviewstats_appointment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.activity'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('participants', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('paid', 'שולם'), ('failed', 'נכשל'), ('refunded', 'הוחזר')], default='pending', max_length=10)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='homePage.activity')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='homePage.booking'),
        ),
    ]
