# Generated by Django 5.2.4 on 2025-08-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0013_sitereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='details',
            field=models.CharField(blank=True, null=True, verbose_name='פרטים/הערות'),
        ),
    ]
