# Generated by Django 5.2.4 on 2025-08-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0014_booking_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
