# Generated by Django 5.2.4 on 2025-08-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0015_delete_pagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'פעילות', 'verbose_name_plural': 'פעילויות'},
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'תור', 'verbose_name_plural': 'תורים'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'הזמנה', 'verbose_name_plural': 'הזמנות'},
        ),
        migrations.AlterModelOptions(
            name='customschedule',
            options={'verbose_name': 'לוח זמנים מיוחד', 'verbose_name_plural': 'לוחות זמנים מיוחדים'},
        ),
        migrations.AlterModelOptions(
            name='sitereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'ביקורת', 'verbose_name_plural': 'ביקורות'},
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='שם מלא')),
                ('phone', models.CharField(max_length=20, verbose_name='טלפון')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל (לא חובה)')),
                ('order_id', models.CharField(max_length=80, verbose_name='מס׳ הזמנה (payment_ref)')),
                ('start_dt', models.DateTimeField(blank=True, null=True, verbose_name='מועד השירות (אם ידוע)')),
                ('reason', models.TextField(blank=True, verbose_name='סיבת ביטול (אופציונלי)')),
                ('channel', models.CharField(choices=[('web', 'אתר'), ('phone', 'טלפון'), ('whatsapp', 'וואטסאפ')], default='web', max_length=20, verbose_name='ערוץ')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('approved', 'אושר'), ('rejected', 'נדחה'), ('refunded', 'זוכה')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב־')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to='homePage.appointment', verbose_name='Appointment')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to='homePage.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'בקשת ביטול עסקה',
                'verbose_name_plural': 'בקשות ביטול עסקה',
                'ordering': ['-created_at'],
            },
        ),
    ]
