# Generated by Django 5.2.4 on 2025-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0017_termsconsent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsconsent',
            options={'verbose_name': 'אישר/ה מדיניות', 'verbose_name_plural': 'אישורי מדיניות'},
        ),
        migrations.RemoveField(
            model_name='termsconsent',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='termsconsent',
            name='user',
        ),
        migrations.AddField(
            model_name='termsconsent',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
