# Generated by Django 5.2.4 on 2025-09-01 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0018_alter_termsconsent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mock', max_length=50)),
                ('amount_agorot', models.PositiveIntegerField()),
                ('currency', models.CharField(default='ILS', max_length=10)),
                ('status', models.CharField(choices=[('created', 'נוצר'), ('pending', 'ממתין'), ('succeeded', 'הצליח'), ('failed', 'נכשל'), ('canceled', 'בוטל'), ('refunded', 'הוחזר')], default='created', max_length=20)),
                ('appointment_id', models.IntegerField(blank=True, null=True)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('participants', models.IntegerField(default=1)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('provider_session_id', models.CharField(blank=True, max_length=120)),
                ('charge_id', models.CharField(blank=True, max_length=120)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('return_url', models.URLField(blank=True)),
                ('cancel_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
