# Generated by Django 5.2.4 on 2025-09-03 12:41

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def clean_charge_ids(apps, schema_editor):
    Payment = apps.get_model('homePage', 'Payment')

    # 1) "" → NULL (אחרי שהעמודה כבר מאפשרת NULL)
    Payment.objects.filter(charge_id="").update(charge_id=None)

    # 2) הסרת כפילויות אמיתיות (להשאיר את הוותיקה, לשאר NULL)
    dups = (
        Payment.objects
        .exclude(charge_id__isnull=True)
        .values('charge_id')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for row in dups:
        cid = row['charge_id']
        qs = Payment.objects.filter(charge_id=cid).order_by('id')
        keep_id = qs.values_list('id', flat=True).first()
        qs.exclude(id=keep_id).update(charge_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0019_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='payment',
                to='homePage.booking'
            ),
        ),

        # שלב 1: קודם לאפשר NULL בלי יוניק (כדי שהניקוי יצליח)
        migrations.AlterField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(max_length=64, null=True, blank=True),
        ),

        # שלב 2: ניקוי נתונים (""→NULL + הסרת כפילויות)
        migrations.RunPython(clean_charge_ids, migrations.RunPython.noop),

        # שלב 3: עכשיו מותר לאכוף יוניק
        migrations.AlterField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(max_length=64, null=True, blank=True, unique=True),
        ),
    ]
