# Generated by Django 5.2.4 on 2025-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0020_payment_booking_alter_payment_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
