# Generated by Django 5.2.4 on 2025-09-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0021_alter_booking_payment_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBoard',
            fields=[
            ],
            options={
                'verbose_name': 'מערכת שעות',
                'verbose_name_plural': 'מערכת שעות',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homePage.booking',),
        ),
    ]
