# Generated by Django 5.2.4 on 2025-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0022_scheduleboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleboard',
            options={'verbose_name': 'לוח שנה', 'verbose_name_plural': 'לוח שנה'},
        ),
        migrations.AddField(
            model_name='customschedule',
            name='allow_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='allow_sunrise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='night_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='night_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='sunrise_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='sunrise_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
