# Generated by Django 5.2.4 on 2025-09-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0023_alter_scheduleboard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback_token',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
