# Generated by Django 5.2.4 on 2025-09-16 10:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0024_booking_feedback_sms_sent_at_booking_feedback_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='homePage.activity', verbose_name='פעילות'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב-'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='מייל'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='טלפון'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_dt',
            field=models.DateTimeField(verbose_name='שעת סיום'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.PositiveIntegerField(default=1, verbose_name='משתתפים'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, verbose_name='שיטת תשלום'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name="מס' הזמנה"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_dt',
            field=models.DateTimeField(verbose_name='שעת התחלה'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('paid', 'שולם'), ('failed', 'נכשל'), ('refunded', 'הוחזר')], default='pending', max_length=10, verbose_name='סטטוס'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='מחיר'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='עודכן ב-'),
        ),
        migrations.AlterField(
            model_name='cancellationrequest',
            name='order_id',
            field=models.CharField(max_length=80, verbose_name='מס׳ הזמנה'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='תגובה'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב-'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג'),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='עודכן ב-'),
        ),
        migrations.AlterField(
            model_name='termsconsent',
            name='accepted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='אושר ב-'),
        ),
        migrations.AlterField(
            model_name='termsconsent',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='שם מלא'),
        ),
        migrations.AlterField(
            model_name='termsconsent',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='termsconsent',
            name='policy',
            field=models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy')], max_length=16, verbose_name='מדיניות'),
        ),
        migrations.AlterField(
            model_name='termsconsent',
            name='subject_id',
            field=models.CharField(db_index=True, max_length=32, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='termsconsent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='user agent'),
        ),
        migrations.AlterField(
            model_name='termsconsent',
            name='version',
            field=models.CharField(max_length=16, verbose_name='גרסה'),
        ),
    ]
