# Generated by Django 5.2.4 on 2025-09-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0025_alter_booking_activity_alter_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='תאריך'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(default=15, verbose_name='אורך'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='נקבע'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_break',
            field=models.BooleanField(default=False, verbose_name='הפסקה'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='שעה'),
        ),
    ]
