# Generated by Django 5.2.4 on 2025-09-25 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0026_alter_appointment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleboard',
            options={'verbose_name': 'לוח שעות - הזמנות', 'verbose_name_plural': 'לוח שעות - הזמנות'},
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='שם מלא של מדריך/ה')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='טלפון')),
                ('active', models.BooleanField(default=True, verbose_name='פעיל/ה')),
                ('color', models.CharField(blank=True, help_text='HEX כמו #42A5F5', max_length=7, verbose_name='צבע בלוח')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'מדריך/ה',
                'verbose_name_plural': 'מדריכים',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('start_time', models.TimeField(verbose_name='שעת התחלה')),
                ('end_time', models.TimeField(verbose_name='שעת סיום')),
                ('customer_full_name', models.CharField(max_length=120, verbose_name='שם מלא של לקוח/ה')),
                ('customer_phone', models.CharField(max_length=32, verbose_name='טלפון לקוח/ה')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל לקוח/ה')),
                ('details', models.TextField(blank=True, verbose_name='פרטים/הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_sessions', to='homePage.instructor', verbose_name='מדריך/ה')),
            ],
            options={
                'verbose_name': 'הזמנה לרכיבה טיפולית',
                'verbose_name_plural': 'לוח שעות - רכיבה טיפולית',
                'ordering': ('-date', 'start_time'),
                'indexes': [models.Index(fields=['date', 'start_time'], name='homePage_tr_date_74d84d_idx')],
            },
        ),
    ]
