# Generated by Django 5.2.4 on 2025-09-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0027_alter_scheduleboard_options_instructor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentsession',
            options={'permissions': [('can_drag_sessions', 'Can drag/resize sessions on calendar'), ('can_create_sessions', 'Can create sessions from calendar')]},
        ),
        migrations.RemoveIndex(
            model_name='treatmentsession',
            name='homePage_tr_date_74d84d_idx',
        ),
    ]
