# Generated by Django 5.2.4 on 2025-09-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0028_alter_treatmentsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentsession',
            options={'ordering': ('-date', 'start_time'), 'permissions': [('can_drag_sessions', 'Can drag/resize sessions on calendar'), ('can_create_sessions', 'Can create sessions from calendar')], 'verbose_name': 'הזמנה לרכיבה טיפולית', 'verbose_name_plural': 'לוח שעות - רכיבה טיפולית'},
        ),
        migrations.AddIndex(
            model_name='treatmentsession',
            index=models.Index(fields=['date', 'start_time'], name='homePage_tr_date_74d84d_idx'),
        ),
    ]
