# Generated by Django 5.2.4 on 2025-09-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0029_alter_treatmentsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentsession',
            options={'ordering': ('-date', 'start_time'), 'permissions': [('can_drag_sessions', 'Can drag/resize sessions on calendar'), ('can_create_sessions', 'Can create sessions from calendar'), ('change_details_only', 'Can change details field only')], 'verbose_name': 'הזמנה לרכיבה טיפולית', 'verbose_name_plural': 'לוח שעות - רכיבה טיפולית'},
        ),
    ]
