# Generated by Django 5.2.4 on 2025-09-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0030_alter_treatmentsession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='payment_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name="מס' עסקה"),
        ),
    ]
