# Generated by Django 5.2.4 on 2025-09-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0031_treatmentsession_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('lesson', 'שיעור רכיבה'), ('therapy', 'רכיבה טיפולית')], default='lesson', max_length=20, verbose_name='סוג מפגש'),
        ),
    ]
