# Generated by Django 5.2.4 on 2025-10-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0032_treatmentsession_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentsession',
            name='feedback_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='נשלח SMS משוב ב-'),
        ),
        migrations.AddField(
            model_name='treatmentsession',
            name='feedback_token',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='אסימון משוב'),
        ),
    ]
