# Generated by Django 5.2.4 on 2025-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0033_treatmentsession_feedback_sms_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customschedule',
            options={'ordering': ('-priority', '-id'), 'verbose_name': 'כלל לוח זמנים', 'verbose_name_plural': 'כללי לוח זמנים'},
        ),
        migrations.AddField(
            model_name='customschedule',
            name='adar_policy',
            field=models.CharField(blank=True, choices=[('AUTO_ADAR2', 'אוטומטי: אדר רגיל / אדר ב׳ בשנה מעוברת'), ('ALWAYS_A1', 'תמיד אדר א׳ (במעוברת) / אדר רגיל (בשאינה)'), ('ALWAYS_A2', 'תמיד אדר ב׳ (במעוברת) / אדר רגיל (בשאינה)')], default='AUTO_ADAR2', max_length=12, verbose_name='מדיניות אדר'),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='h_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='יום בחודש'),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='h_month',
            field=models.CharField(blank=True, choices=[('TISHREI', 'תשרי'), ('CHESHVAN', 'חשוון'), ('KISLEV', 'כסלו'), ('TEVET', 'טבת'), ('SHEVAT', 'שבט'), ('ADAR', 'אדר'), ('NISAN', 'ניסן'), ('IYAR', 'אייר'), ('SIVAN', 'סיוון'), ('TAMMUZ', 'תמוז'), ('AV', 'אב'), ('ELUL', 'אלול'), ('ADAR_I', 'אדר א׳'), ('ADAR_II', 'אדר ב׳')], max_length=10, verbose_name='חודש עברי'),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='kind',
            field=models.CharField(choices=[('GREGORIAN', 'תאריך לועזי'), ('HEBREW', 'תאריך עברי חוזר')], default='GREGORIAN', max_length=10, verbose_name='סוג כלל'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customschedule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='שם (לא חובה)'),
        ),
        migrations.AddField(
            model_name='customschedule',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text='גבוה יותר → גובר בהתנגשות בין כללים.', verbose_name='עדיפות'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='allow_night',
            field=models.BooleanField(default=False, verbose_name='לאפשר לילה'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='allow_sunrise',
            field=models.BooleanField(default=False, verbose_name='לאפשר זריחה'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך (לועזי)'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='שעת סיום'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='is_active',
            field=models.BooleanField(default=False, help_text='סמן/י אם עובדים ביום הזה. כיבוי = חסום לגמרי.', verbose_name='יום פעיל?'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='night_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='לילה - סיום'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='night_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='לילה - התחלה'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='שעת התחלה'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='sunrise_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='זריחה - סיום'),
        ),
        migrations.AlterField(
            model_name='customschedule',
            name='sunrise_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='זריחה - התחלה'),
        ),
        migrations.AddIndex(
            model_name='customschedule',
            index=models.Index(fields=['kind', 'date'], name='homePage_cu_kind_5442cc_idx'),
        ),
        migrations.AddIndex(
            model_name='customschedule',
            index=models.Index(fields=['kind', 'h_month', 'h_day'], name='homePage_cu_kind_c459d2_idx'),
        ),
        migrations.AddIndex(
            model_name='customschedule',
            index=models.Index(fields=['priority'], name='homePage_cu_priorit_2eb3a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='customschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'GREGORIAN')), fields=('date',), name='uniq_customschedule_greg_date'),
        ),
        migrations.AddConstraint(
            model_name='customschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'HEBREW')), fields=('h_month', 'h_day', 'adar_policy'), name='uniq_customschedule_hebrew_combo'),
        ),
    ]
