# Generated by Django 5.2.4 on 2025-10-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0034_alter_customschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customschedule',
            options={'ordering': ('-id',), 'verbose_name': 'כלל לוח זמנים', 'verbose_name_plural': 'כללי לוח זמנים'},
        ),
        migrations.RemoveIndex(
            model_name='customschedule',
            name='homePage_cu_priorit_2eb3a0_idx',
        ),
        migrations.RemoveField(
            model_name='customschedule',
            name='priority',
        ),
        migrations.AddField(
            model_name='customschedule',
            name='repeat_every_year',
            field=models.BooleanField(default=False, verbose_name='לחזור כל שנה?'),
        ),
    ]
