# Generated by Django 5.2.4 on 2025-10-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0035_alter_customschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customschedule',
            options={'ordering': ('-id',), 'verbose_name': 'שינוי שעות יום עבודה', 'verbose_name_plural': 'שינוי שעות יום עבודה'},
        ),
    ]
