# Generated by Django 5.2.4 on 2025-10-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0036_alter_customschedule_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
            ],
            options={
                'verbose_name': 'סיכום חודש',
                'verbose_name_plural': 'סיכום חודש',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homePage.booking',),
        ),
    ]
