# Generated by Django 5.2.4 on 2025-11-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0037_monthlysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16, verbose_name='גרסה')),
                ('channel', models.CharField(choices=[('sms', 'SMS / טלפון'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16, verbose_name='ערוץ')),
                ('subject_id', models.CharField(db_index=True, max_length=64, verbose_name='מזהה נושא')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='שם מלא')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='מייל')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='אושר ב-')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
            ],
            options={
                'unique_together': {('channel', 'subject_id', 'version')},
            },
        ),
    ]
