# Generated by Django 5.2.4 on 2026-02-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0039_appointment_hold_created_at_appointment_hold_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
