# Generated by Django 5.2.4 on 2026-02-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0040_appointment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hold_created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hold_token',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hold_until',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='hold_token',
        ),
    ]
