# Generated by Django 5.2.4 on 2026-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0041_remove_appointment_hold_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hold_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hold_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
