# Generated by Django 5.2.4 on 2026-02-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0042_appointment_hold_token_appointment_hold_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hold_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
