# Generated by Django 5.2.4 on 2026-02-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0043_appointment_hold_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
