# Generated by Django 5.2.4 on 2026-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0045_appointment_hold_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('basic', 'מתחילים'), ('advanced', 'מתקדמים'), ('white', 'סוס לבן'), ('brown', 'סוס חום'), ('couple', 'רכיבה זוגית ביום'), ('couple_sunrise', 'רכיבה זוגית בזריחה'), ('couple_night', 'רכיבה זוגית בלילה'), ('couple_picnic', 'רכיבה זוגית פיקניק'), ('none', 'ללא סוג')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='cancellationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('approved', 'ממתין להחזר'), ('rejected', 'נדחה'), ('refunded', 'זוכה')], default='pending', max_length=20, verbose_name='סטטוס'),
        ),
    ]
