# Generated by Django 5.2.4 on 2026-08-04 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0047_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='activity_name',
        ),
        migrations.AddField(
            model_name='receipt',
            name='cheque_bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cheque_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cheque_due_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='receipt',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'מזומן'), ('credit', 'אשראי'), ('bank_transfer', 'העברה בנקאית'), ('cheque', 'שיק'), ('bit', 'ביט'), ('paybox', 'פייבוקס')], default='credit', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='homePage.payment'),
        ),
    ]
