# Generated by Django 5.2.4 on 2026-08-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0048_remove_receipt_activity_name_receipt_cheque_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
