# Generated by Django 5.2.4 on 2026-08-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0049_alter_receipt_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_booking_enabled', models.BooleanField(default=False, help_text="כשהתיבה לא מסומנת — כל דפי הפעילויות באתר יציגו רק פרטים ותמונות (כמו עמוד 'צילומים' היום), בלי לוח תורים להזמנה עצמאית. מיועד לסגירה זמנית של הזמנות אונליין.", verbose_name='אפשר הזמנת תורים דרך האתר')),
            ],
            options={
                'verbose_name': 'הגדרות אתר',
                'verbose_name_plural': 'הגדרות אתר',
            },
        ),
    ]
