# Generated by Django 5.2.4 on 2026-08-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0050_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_void',
            field=models.BooleanField(default=False, help_text='לסימון קבלה שגויה/כפולה כמבוטלת. המספור לא משתנה — כך נשמר רצף תקין.', verbose_name='קבלה מבוטלת'),
        ),
    ]
