# Generated by Django 5.2.4 on 2026-08-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0051_receipt_is_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_no_notify_checkbox',
            field=models.BooleanField(default=True, help_text='כשהתיבה לא מסומנת — האפשרות הזו לא תופיע באשף יצירת ההזמנה באדמין.', verbose_name='הצג באשף יצירת הזמנה אפשרות "ללא שליחת מייל, SMS וללא קבלה"'),
        ),
    ]
