# Generated by Django 5.2.4 on 2026-08-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0052_sitesettings_show_no_notify_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_no_receipt_checkbox',
            field=models.BooleanField(default=True, help_text='כשהתיבה לא מסומנת — האפשרות הזו לא תופיע במסך סימון הזמנה כשולם.', verbose_name='הצג במסך "סמן כשולם" אפשרות "ביטול יצירת קבלה חדשה"'),
        ),
    ]
