# Generated by Django 5.2.4 on 2026-08-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0053_sitesettings_show_no_receipt_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='shabbat_closure_enabled',
            field=models.BooleanField(default=True, help_text='כשהתיבה מסומנת — האתר ייסגר אוטומטית ללקוחות בכניסת שבת/חג (לפי זמני ירושלים) ועד צאתם, ויוצג עמוד "האתר סגור".', verbose_name='חסום את האתר בשבתות וחגים'),
        ),
    ]
