# Generated by Django 5.2.4 on 2026-08-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0054_sitesettings_shabbat_closure_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOnlyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='לתאריך חד-פעמי – התאריך המדויק. לתאריך חוזר כל שנה – רק היום והחודש נלקחים בחשבון.', verbose_name='תאריך')),
                ('repeat_every_year', models.BooleanField(default=False, verbose_name='לחזור כל שנה?')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל?')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='הערה (לא חובה)')),
            ],
            options={
                'verbose_name': 'תאריך להזמנות טלפוניות בלבד',
                'verbose_name_plural': 'תאריכים להזמנות טלפוניות בלבד',
                'ordering': ('-repeat_every_year', 'date'),
            },
        ),
    ]
