# Generated by Django 5.2.4 on 2026-08-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0055_add_phone_only_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneonlydate',
            name='end_date',
            field=models.DateField(blank=True, help_text="השאירו ריק ליום בודד. למילוי – הכלל חל על כל הימים בין 'מתאריך' ל'עד תאריך' (כולל שני הקצוות).", null=True, verbose_name='עד תאריך (כולל) – לא חובה'),
        ),
        migrations.AlterField(
            model_name='phoneonlydate',
            name='date',
            field=models.DateField(help_text='לתאריך חד-פעמי – התאריך המדויק. לתאריך חוזר כל שנה – רק היום והחודש נלקחים בחשבון.', verbose_name='מתאריך'),
        ),
    ]
