# Generated by Django 5.2.4 on 2026-08-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0056_phone_only_date_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneonlydate',
            name='adar_policy',
            field=models.CharField(blank=True, choices=[('AUTO_ADAR2', 'אוטומטי: אדר רגיל / אדר ב׳ בשנה מעוברת'), ('ALWAYS_A1', 'תמיד אדר א׳ (במעוברת) / אדר רגיל (בשאינה)'), ('ALWAYS_A2', 'תמיד אדר ב׳ (במעוברת) / אדר רגיל (בשאינה)')], default='AUTO_ADAR2', max_length=12, verbose_name='מדיניות אדר'),
        ),
        migrations.AddField(
            model_name='phoneonlydate',
            name='h_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='יום בחודש עברי'),
        ),
        migrations.AddField(
            model_name='phoneonlydate',
            name='h_end_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='יום בחודש עברי - עד (לא חובה)'),
        ),
        migrations.AddField(
            model_name='phoneonlydate',
            name='h_end_month',
            field=models.CharField(blank=True, choices=[('TISHREI', 'תשרי'), ('CHESHVAN', 'חשוון'), ('KISLEV', 'כסלו'), ('TEVET', 'טבת'), ('SHEVAT', 'שבט'), ('ADAR', 'אדר'), ('NISAN', 'ניסן'), ('IYAR', 'אייר'), ('SIVAN', 'סיוון'), ('TAMMUZ', 'תמוז'), ('AV', 'אב'), ('ELUL', 'אלול'), ('ADAR_I', 'אדר א׳'), ('ADAR_II', 'אדר ב׳')], max_length=10, verbose_name='חודש עברי - עד (לא חובה)'),
        ),
        migrations.AddField(
            model_name='phoneonlydate',
            name='h_month',
            field=models.CharField(blank=True, choices=[('TISHREI', 'תשרי'), ('CHESHVAN', 'חשוון'), ('KISLEV', 'כסלו'), ('TEVET', 'טבת'), ('SHEVAT', 'שבט'), ('ADAR', 'אדר'), ('NISAN', 'ניסן'), ('IYAR', 'אייר'), ('SIVAN', 'סיוון'), ('TAMMUZ', 'תמוז'), ('AV', 'אב'), ('ELUL', 'אלול'), ('ADAR_I', 'אדר א׳'), ('ADAR_II', 'אדר ב׳')], max_length=10, verbose_name='חודש עברי'),
        ),
        migrations.AddField(
            model_name='phoneonlydate',
            name='kind',
            field=models.CharField(choices=[('GREGORIAN', 'תאריך לועזי'), ('HEBREW', 'תאריך עברי חוזר')], default='GREGORIAN', max_length=10, verbose_name='סוג תאריך'),
        ),
        migrations.AlterField(
            model_name='phoneonlydate',
            name='date',
            field=models.DateField(blank=True, help_text='לתאריך חד-פעמי – התאריך המדויק. לתאריך חוזר כל שנה – רק היום והחודש נלקחים בחשבון.', null=True, verbose_name='מתאריך (לועזי)'),
        ),
        migrations.AlterField(
            model_name='phoneonlydate',
            name='end_date',
            field=models.DateField(blank=True, help_text="השאירו ריק ליום בודד. למילוי – הכלל חל על כל הימים בין 'מתאריך' ל'עד תאריך' (כולל שני הקצוות).", null=True, verbose_name='עד תאריך לועזי (כולל) – לא חובה'),
        ),
        migrations.AlterField(
            model_name='phoneonlydate',
            name='repeat_every_year',
            field=models.BooleanField(default=False, verbose_name='לחזור כל שנה? (לועזי)'),
        ),
    ]
