# Generated by Django 5.2.4 on 2026-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0057_phone_only_date_hebrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='booking_break_enabled',
            field=models.BooleanField(default=True, help_text='כשהתיבה מסומנת — אחרי כל הזמנה שאורכת יותר מ-30 דקות, המערכת שומרת אוטומטית רבע שעה נוספת כהפסקה שבה אי אפשר להזמין תור. כשהתיבה לא מסומנת — לא תישמר הפסקה, וניתן יהיה להזמין תור מיד בסיום ההזמנה הקודמת.', verbose_name='הוסף הפסקה של רבע שעה אחרי הזמנות ארוכות (מעל 30 דקות)'),
        ),
    ]
