# Generated by Django 5.2.4 on 2026-09-13 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0058_sitesettings_booking_break_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_review_id', models.CharField(max_length=255, unique=True, verbose_name='מזהה ביקורת בגוגל')),
                ('reviewer_name', models.CharField(blank=True, max_length=120, verbose_name='שם המגיב')),
                ('reviewer_photo_url', models.URLField(blank=True, verbose_name='תמונת המגיב')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג')),
                ('comment', models.TextField(blank=True, verbose_name='תגובה')),
                ('reply_comment', models.TextField(blank=True, verbose_name='תשובת החווה')),
                ('create_time', models.DateTimeField(verbose_name='נכתב ב-')),
                ('update_time', models.DateTimeField(verbose_name='עודכן ב-')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='סונכרן ב-')),
            ],
            options={
                'verbose_name': 'ביקורת גוגל',
                'verbose_name_plural': 'ביקורות גוגל',
                'ordering': ['-create_time'],
            },
        ),
    ]
